# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('year', models.IntegerField(max_length=3)),
                ('month', models.IntegerField(max_length=3)),
                ('rate', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mortgage_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage.User'),
        ),
    ]
