# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='loan',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='year',
            field=models.IntegerField(),
        ),
    ]
