# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_auto_20180117_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mortgage_name',
        ),
    ]
