# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0004_loan_loan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='rate',
            field=models.FloatField(),
        ),
    ]
