# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_auto_20180118_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='down_payment',
            field=models.FloatField(default=0),
        ),
    ]
