# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0006_loan_down_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='add_per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='add_per_year',
            field=models.FloatField(default=0),
        ),
    ]
