# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0007_auto_20180124_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(default=0),
        ),
    ]
