# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0008_auto_20180124_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='add_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='add_per_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
